### PR TITLE
Don't cache secrets in potentially insecure RAM

### PR DESCRIPTION
**Pull request by seamusabshere**
hey @erithmetic !

### CODE REVIEW

**Comment by erithmetic** [comment]
Hi @seamusabshere, thanks for the contribution! 

The original vision for this was to set a TTL on cached secrets (possibly also enforced by vault/etc. when making the initial request). Otherwise, an app could be severely slowed by making network calls to secret stores.

At the very least, can we make this configurable? Maybe have a customizable TTL and just set it to 0?

**Comment by seamusabshere** [comment]
hey @erithmetic 

i think the app itself should be in charge of caching secrets if that's necessary instead of us...

**Comment by erithmetic** [comment]
Caching and TTL settings definitely fall in the realm of "secrets management," which is what this gem is for. I've really wanted this TTL feature the entire time. I'll plan on implementing this, but might not get to it until next week.

Feel free to fork if you need something that fits your use case.

**Comment by seamusabshere** [comment]
done in https://github.com/faradayio/secretfile_ruby - thanks!

**Pull request closed without merging**
